dist: trusty
sudo: required

language: go
go:
- '1.8'
deploy:
  provider: heroku
  after_script:
    go get -u github.com/tools/godep && godep save .
  app: 
    master: around-you-backend
  api_key:
    master:
      secure: IC6t3gDygNTvfLl8n/U0DCmd4krpPMWlI1ENwrNqhb94zxBdVaj/H4VvNZjO0KicesGQBicGnOLaGsasJVvVtMNp1LZ7hbqwYK1+/Of2Bi/oGwuEHqCXTt4mGOcIJWXbCMdzcfYQyCcSfGGOZXYWZbAFVt2ErGFBFmKT3A5E0Fpel7lqocjnfLR0pctUVaHtg4KGvJj0SGRtYMInGyUzGTISIQb7jif0+WEXJthg/SzpMNxLlhiLn1qRg3m+9WDMZB+jBF6lEiVoZbST6TRcvp9iuE1/YNbukCXX8NJ8lvM9uoDpL1LRIU+0eFkfgpHOv+NiH02TErslx6hQBA6LPxSC3SXTIFHpNN9zImWTEziiZT29mFpN+IZlMK3w9iS0CPDFWmdPFgXH1nNgLSKdAis6O+eiP89KgPfzvxSvUmxlewNFz7ZSWAifbs8hl7nrj/f8KzUXL64DT0D/lnAhvtwKoUiZUORsUgiX2PDdp/3em8OcNw2kTkpUnjF/3isHpbS0aYzOKXPzcDUNdqqvrNzNIBZYUWCwJI0pv+BRRKRXrTcMbto/oeVk04c0IC9ccX5bbigFqc6qU8BPTZBLvHu8vEG5hZOLuHStLoCYZ7ws96G7sbXu5CThmjF+sCoHbc18R57t8Y6misJ/oqeTUM7x4t242ydyBuZ6lw5IXHY=