language: go
go:
- '1.8'
deploy:
  api_key:
    secure: V4SCZlG2zBHRqGp4pqQBxPyzmTU5Gr4Ak1zd/hqoCpVazLowIyBP3gK6RAa61YX7IXoI43MbAgQ0O7KRGVE2ZfPALUjNGW9w2yGCxAur/cJd3h4n4zU/9NWAn2ZnFvSrRMJ8TOgfvDg2raMFWwU6YWJZ/dWxXWzvRYpSTSC63BeLbexrjnZVufAOCLrtddXZwSx+TPcwdXyus0P55+BPQysaNmSgigZKfYp0d5Lsdy/ttsfR/Ynht+4wGNvqWJfGHaOP3/tj/sdkGcwndwrbjYaRXQmlAuWwW6vFv1nTke6Avo38sTB03+MJkO/H6rzXxTzfQ3mwP87mDxHzb/uU2qQOZmnTmE/YrdEX/fHuroRELhq5LvWL3PgT7JTSbwIo7JUnHqhmKmCkyWpZ8aB+VgLhgDMxqK6g4TZOc3ktQ09cfYZqWe6Ls1V4St65L45QYXfwNHU7d/g9+jMZxTdy3ZEY5x+9RYmE+/E2yIF1U3HD4MV8+6GW+m4O+b0KPYAzbINw7oXTVHj6sFvxy9a5d9JAgndble0KR/k6iOSqIei+U19tEILPo1wGTXzV98k1R7D2fco8l2nPBzNRYX86CBC03mDSUQLFnRxks/mt5VRjK/yb7GnZPe2NmIckoPweIAamj8U9q2WnXrjIfZuwWKywGJ26h01Gr0msBaiYiUo=
